name: Kolibri Wonka
markdown: redcarpet

defaults:
  -
    values:
      layout: "default"
      title: "Wonka - Vinnukúltúr Kolibri"

collections:
  docs:
    output: true

sass:
    sass_dir: _sass
    style: :compressed
